version: '3'

services:

  ers-api:
    build:
      context: ./ers-api
      dockerfile: Dockerfile
    container_name: ers-api
    image: ers-api
    hostname: ers-api
    tty: true
    ports:
      - '8081:8081'
    depends_on:
      - fake-api-hospital

  ers-gateway:
    build:
      context: ./ers-gateway
      dockerfile: Dockerfile
    container_name: ers-gateway
    image: ers-gateway
    hostname: ers-gateway
    tty: true
    ports:
      - '80:80'
    depends_on:
      - ers-api

  fake-api-hospital:
    build:
      context: ./fake-api-hospital
      dockerfile: Dockerfile
    container_name: fake-api-hospital
    image: fake-api-hospital
    hostname: fake-api-hospital
    tty: true
    ports:
      - '8082:8082'

  test-e2e:
    depends_on:
      - ers-api
      - ers-gateway
      - fake-api-hospital
    build:
      context: ./test-e2e
      dockerfile: Dockerfile
    container_name: test-e2e
    image: test-e2e
    hostname: test-e2e
    tty: true
    ports:
      - '8080:8080'
