version: '3'

services:

  # redis:
  #   image: ers-redis
  #   container_name: ers-redis
  #   hostname: ers-redis
  #   ports:
  #     - 4025:6379
     
  # phpmyadmin:
  #   depends_on:
  #     - mysql
  #   image: phpmyadmin
  #   ports:
  #     - '9090:80'
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: root
 
  # ers-api-mysql:
  #   image: mysql:8.0
  #   container_name: ers-api-mysql
  #   command: mysqld --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - mysql-data:/var/local/mysql/data
  #     # - ./ers-api/data/mysql-dump:/docker-entrypoint-initdb.d
  #   ports:
  #     - 3306:3306
  #   hostname: ers-api-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: testdb
  #     MYSQL_USER: testuser
  #     MYSQL_PASSWORD: root
      
  ers-api:
    build:
      context: ./ers-api
      dockerfile: Dockerfile
    container_name: ers-api
    image: ers-api
    hostname: ers-api
    tty: true
    ports:
      - '8081:8081'
    # depends_on:
    #   - ers-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root

  ers-gateway:
    build:
      context: ./ers-gateway
      dockerfile: Dockerfile
    container_name: ers-gateway
    image: ers-gateway
    hostname: ers-gateway
    tty: true
    ports:
      - '80:80'
    depends_on:
      - ers-api

  # fake-api-hospital:
  #   build: fake-api-hospital
  #   image: fake-api-hospital
  #   container_name: fake-api-hospital
  #   hostname: fake-api-hospital
  #   tty: true
  #   ports:
  #     - '8082:8082'

# volumes:
#   mysql-data:
#     driver: local