

name: Test ERS API with Maven

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  applicationfolder: ers-api

jobs:

  build:
    name: Test ERS API with Maven

    runs-on: ubuntu-20.04

    permissions: write-all

    # defaults:
    #   run:
    #     working-directory: ${{ env.applicationfolder }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Build with Maven
        working-directory: ${{ env.applicationfolder }}
        # --batch-mode : will automatically use default values instead of asking you via prompt for those values
        # -DskipTests : skipping the tests
        run: mvn --batch-mode -DskipTests clean package
      
      - name: Test
        working-directory: ${{ env.applicationfolder }}
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      # https://github.com/dorny/test-reporter
      - name: Report
        uses: dorny/test-reporter@v1.5.0
        if: always()
        # if: success() || failure()
        with:
          name: Maven Tests
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit
          fail-on-error: true
      
      ## Utilisation de scripts
      # - name: chmod
      #   run: chmod -R +x ./.github
      # 
      # - name: Build and Package Maven
      #   id: package
      #   working-directory: ${{ env.applicationfolder }}
      #   run: $GITHUB_WORKSPACE/.github/scripts/build.sh

