

name: Pipeline CI/CD

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  ersapi:
    name: ERS-API Test

    runs-on: ubuntu-20.04

    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Build with Maven
        working-directory: ./ers-api/
        # --batch-mode : will automatically use default values instead of asking you via prompt for those values
        # -DskipTests : skipping the tests
        run: mvn --batch-mode -DskipTests clean package
      
      - name: Test
        working-directory: ./ers-api/
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      # https://github.com/dorny/test-reporter
      - name: Report
        uses: dorny/test-reporter@v1.5.0
        if: always()
        # if: success() || failure()
        with:
          name: ERS-API Test results
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit
          fail-on-error: true
     
      
  ersgateway:
    name: ERS-GATEWAY Test

    runs-on: ubuntu-20.04

    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Build with Maven
        working-directory: ./ers-gateway/
        # --batch-mode : will automatically use default values instead of asking you via prompt for those values
        # -DskipTests : skipping the tests
        run: mvn --batch-mode -DskipTests clean package
      
      - name: Test
        working-directory: ./ers-gateway/
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      # https://github.com/dorny/test-reporter
      - name: Report
        uses: dorny/test-reporter@v1.5.0
        if: always()
        # if: success() || failure()
        with:
          name: ERS-GATEWAY Test results
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit
          fail-on-error: true
      